# .travis.yml for Travis CI
# https://docs.travis-ci.com/user/languages/r
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
r:
#  - oldrel
  - release
  - devel
cache: packages
# helpful when preparing your package for submission to CRAN
warnings_are_errors: false
# No need for sudo as R is natively supported now.
sudo: false

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
